### ISSUE TITLE
Idea: Support /efi as the base instead of /boot

### ISSUE THREAD

**Issue by kpfleming** [gregory-lee-bartholomew/bootsync#1]
Thanks for this! I found it via the issue you opened in the systemd repo, since I'm in a similar situation to yours.

However, I'm using Debian, and on Debian systems the /boot directory gets a copy of the kernel, symbol map file, and initramfs during installation of a kernel package; the necessary files are then copied into the ESP via a script in /etc/kernel/postinst.d. As a result, I keep my ESP mounted at /efi instead of /boot, because I don't want this stuff in there, since it is unrelated to the BLS and will never be used.

Would you consider some sort of patch to these scripts to allow them to be configured to use /efi as the base directory instead of /boot?

**Comment by gregory-lee-bartholomew** [comment]
Hi Kevin.

Unfortunately, I'm not a Debian user and I don't have much time to familiarize myself with it. You are welcome of course to fork these scripts and attempt to make a version that works on Debian. They heavily rely on the BLS layout (they key on the machine id to know what files to replicate to the other ESPs).

I consider these scripts more of a hack to get by on until something better and official comes along. I've seen many mentions of this problem (specifically [here](https://lwn.net/Articles/912619/)), so hopefully it won't be long before there is official support for this.

**Comment by kpfleming** [comment]
There won't be any need for you to understand Debian :-) The BLS layout is exactly the same.

sd-boot itself supports the ESP being located at /boot, /boot/efi, or /efi, and I've chosen /efi for my systems. The patch I'm suggesting would just provide a variable in the Makefile (defaulting to `/boot`) to allow the user to specify the path they are using for the ESP.

**Comment by gregory-lee-bartholomew** [comment]
If you can test that that works properly on your Debian system and submit a PR, I'd be happy to incorporate that addition in the scripts that I have here. Just have the variable default to /boot and include a comment above it that it can be changed to /efi if that is where you mount your ESP.

Beware that I think there is another bug in these scripts currently where they don't sync the first time if the target ESP(s) are completely empty. I haven't verified that bug yet, but someone reported to me that that was the case. I do know that they work properly to keep things synchronized once there are two fully-functional/populated ESPs to keep synchronized. I intend to fix the empty efi parition case "soon".

**Comment by kpfleming** [comment]
I can confirm that if the target ESPs do not contain the machine-id directory (and a kernel subdirectory below it) the `bootsync` script will not attempt to copy anything into them. I'd be happy to fix that in another PR if you wish.

The `bootsync` script also does not copy *all* of the content from the active ESP to the ESP targets; the boot loader files and various other things are not copied. That may have been intentional in your design, but it means that the target ESP isn't a complete backup and won't work to boot the system. I *think* it would work fine if someone ran `bootctl --esp-path=<target> install` before running `bootsync` the first time, but then the bootloader in the ESP targets wouldn't be updated when `systemd-boot-update.service` updates the active ESP.

**Comment by gregory-lee-bartholomew** [comment]
> I can confirm that if the target ESPs do not contain the machine-id directory (and a kernel subdirectory below it) the `bootsync` script will not attempt to copy anything into them. I'd be happy to fix that in another PR if you wish.

Ah, I see. Thanks. I know what happened now. It used to be that the `bootctl install` command would pre-create that top-level machine id directory. That error can be safely ignored in the script just by adding `|| :` to the end of that particular command. I'll take care of that. I have some other tweaks I'd like to make as well.

> The bootsync script also does not copy all of the content from the active ESP to the ESP targets; the boot loader files and various other things are not copied. That may have been intentional in your design, but it means that the target ESP isn't a complete backup and won't work to boot the system. I think it would work fine if someone ran bootctl --esp-path=<target> install before running bootsync the first time, but then the bootloader in the ESP targets wouldn't be updated when systemd-boot-update.service updates the active ESP.

Yes. That was by design. My understanding from [the original thread where you found the link to this repo](https://github.com/systemd/systemd/issues/19668#issuecomment-846377608) was that rerunning `bootctl --esp-path=<target> update` manually when necessary was the better/safer/preferred way to update the bootloader when necessary.

I think that makes sense. I can see where things might not work if the bootloader is just copied from one partition to the other. Especially since it can tweak firmware settings as part of its installation/update process. (For example, I could see where it might need to update a key in the firmware if secure boot is enabled).

It might be safer to leave the bootloader alone on the fallback ESP. Presumably it was proven to work when the user initially set things up. I know that that was the default behavior for Grub on Fedora Linux -- it *never* reinstalled/updated the bootloader unless the user manually ran `grub2-install <path-to-device>`; even across system upgrades.

I'm open to suggestions on how this should be handled. Thanks for all your help! I'll merge your pull request. 🙂
